### ISSUE TITLE
Missing 'STR' field

### ISSUE THREAD

**Issue by lancour** [cc2qe/svtyper#4]
Hey,
I am trying to convert site specific vcfs to genotyped vcfs using svtyper. The issue I am running into is that some of them get a key error corresponding to a 'STR' key. Is this a start value? What variant caller(s) do you use that can create the STR value in the .vcf file? Thanks.

P.S. you can close this and email me if you want, my email is on my profile.

**Comment by cc2qe** [comment]
Hi Dan,

The STR key is our VCF INFO tag referring to strand orientation for the variant. SVTyper was designed to work with the [LUMPY](https://github.com/arq5x/lumpy-sv/) SV detector, with LUMPY output converted to VCF with [this script](https://github.com/hall-lab/svtools/blob/master/bedpeToVcf). 

I realize that this workflow is convoluted and restrictive. We are actively developing LUMPY to directly output a VCF file that SVTyper can process. I will also update SVTyper to infer strand from the standard VCF fields, rather than our homebrewed "STR" tag, and I'll let you know when it's ready.

--Colby

**Comment by cc2qe** [comment]
Commit https://github.com/cc2qe/svtyper/commit/5099f82578f9bc177bb28d6bc637f76941a0e4b4 ought to make SVTyper more robust to generic VCF files. No longer requiring STR in the info field.

However, I haven't tested this on many VCFs outside of the LUMPY framework, so if you still run into problems, just email me a portion of your VCF. (cc2qe at virginia dot edu)
